version: 0.2            
phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - aws cloudformation --template-file samTemplate.yaml --s3-bucket gourav-labmda-pipeline --output-template-file outputSamTemplate.yaml

artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamTemplate.yaml
  
